In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('D:/Pandora Box/dataset benh.csv')
data[6:10]

,ID benh nhan,Dinh luong Ure (2.5-7.5 mmol/L),Danh gia,Dinh luong Creatinin (60-104 mmol/L),Danh gia.1,Nong do glucose (50-200mg/dL),Danh gia.2,Nong do acid uric ( 180-420 mmol/l),Danh gia.3,Luong glucose huyet thanh trung binh HbA1c (50-137mg/dL),Danh gia.4,Dinh luong d nieu (protein nuoc tieu) 24 gio (50-200mg/l/24h),Danh gia.5,Chan doan benh,Phong kham,So cho trong (1-10),So nguoi trong phong,DF,Thoi gian kh TB (phut),Thoi gian kham
6,62,2.1,Thap,57,Thap,255,Cao,134,Thap,144,Cao,38,Thap,Tieu duong,202,7,3,"[0, 0, 2, 0, 2, 0, 0]",11,10.01
7,215,9.1,Cao,143,Cao,195,Trung binh,427,Cao,69,Trung binh,243,Cao,Suy than,301,4,6,"[2, 2, 1, 2, 1, 2, 2]",17,10.11
8,119,4.5,Trung binh,67,Trung binh,56,Trung binh,479,Cao,63,Trung binh,82,Trung binh,Gut,103,4,6,"[1, 1, 1, 2, 1, 1, 1]",15,10.21
9,344,4.3,Trung binh,61,Trung binh,188,Trung binh,371,Trung binh,112,Trung binh,84,Trung binh,Khong,Khong,Khong,Khong,"[1, 1, 1, 1, 1, 1, 3]",Khong,10.31

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 20 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   ID benh nhan                                                   350 non-null    int64
 1   Dinh luong Ure (2.5-7.5 mmol/L)                                350 non-null    float64
 2   Danh gia                                                       350 non-null    object
 3   Dinh luong Creatinin (60-104 mmol/L)                           350 non-null    int64
 4   Danh gia.1                                                     350 non-null    object
 5   Nong do glucose (50-200mg/dL)                                  350 non-null    int64
 6   Danh gia.2                                                     350 non-null    object
 7   Nong do acid uric ( 180-420 mmol/l)                            350 non-null    int64
 8   Danh gia.3                                                     350 non-null    object
 9   Luong glucose huyet thanh trung binh HbA1c (50-137mg/dL)       350 non-null    int64
 10  Danh gia.4                                                     350 non-null    object
 11  Dinh luong d nieu (protein nuoc tieu) 24 gio (50-200mg/l/24h)  350 non-null    int64
 12  Danh gia.5                                                     350 non-null    object
 13  Chan doan benh                                                 350 non-null    object
 14  Phong kham                                                     350 non-null    object
 15  So cho trong (1-10)                                            350 non-null    object
 16  So nguoi trong phong                                           350 non-null    object
 17  DF                                                             350 non-null    object
 18  Thoi gian kh TB (phut)                                         350 non-null    object
 19  Thoi gian kham                                                 350 non-null    float64
dtypes: float64(2), int64(6), object(12)
memory usage: 54.8+ KB

Không có missing values.

In [4]:
data.describe()

,ID benh nhan,Dinh luong Ure (2.5-7.5 mmol/L),Dinh luong Creatinin (60-104 mmol/L),Nong do glucose (50-200mg/dL),Nong do acid uric ( 180-420 mmol/l),Luong glucose huyet thanh trung binh HbA1c (50-137mg/dL),Dinh luong d nieu (protein nuoc tieu) 24 gio (50-200mg/l/24h),Thoi gian kham
count,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000
mean,174.500000,4.976857,82.380000,141.897143,371.414286,100.557143,128.240000,6.727429
std,101.180532,2.974342,34.095537,80.627416,118.375912,50.878989,78.902861,3.503974
min,0.000000,1.000000,21.000000,16.000000,130.000000,15.000000,12.000000,1.010000
25%,87.250000,2.300000,55.250000,71.000000,269.750000,54.000000,44.250000,3.510000
50%,174.500000,4.300000,81.000000,140.000000,427.000000,101.500000,130.000000,6.460000
75%,261.750000,7.875000,109.000000,210.750000,460.000000,144.000000,204.750000,10.010000
max,349.000000,10.500000,145.000000,290.000000,520.000000,189.000000,249.000000,12.510000

Các giá trị không có gì bất thường.

In [5]:
# Các features đã được xử lý thành categorical variables với 3 mức 'Thấp', 'Trung bình', 'Cao'.

cols_X = ['Danh gia', 'Danh gia.1', 'Danh gia.2', 'Danh gia.3', 'Danh gia.4', 'Danh gia.5']
col_y = ['Chan doan benh']

In [6]:
X = data[cols_X] # features
y = data[col_y] # target

In [7]:
X.describe()

          Danh gia  Danh gia.1  Danh gia.2 Danh gia.3  Danh gia.4  Danh gia.5
count          350         350         350        350         350         350
unique           3           4           3          3           3           3
top     Trung binh  Trung binh  Trung binh        Cao  Trung binh  Trung binh
freq           151         101         151        201         174         151

Có thể thấy Danh gia.1 có 1 giá trị ngoài 3 giá trị Thấp, Cao, Trung bình.

In [8]:
X['Danh gia.1'].unique()

array(['Thap', 'Cao', 'Trung binh', 'Trung binh '], dtype=object)

Do lỗi khi nhập dữ liệu, ta sẽ xử lý lại nó.

In [9]:
X['Danh gia.1'] = pd.DataFrame(['Trung binh' for x in X['Danh gia.1'] if x == 'Trung binh '])

# X['Danh gia.1'] = X['Danh gia.1'].apply(lambda x: 'Trung binh' if x == 'Trung binh ')
# Không thể dùng apply() vì lambda nếu có if sẽ yêu cầu thêm else

In [10]:
X.head()

  Danh gia  Danh gia.1 Danh gia.2 Danh gia.3  Danh gia.4 Danh gia.5
0     Thap  Trung binh       Thap        Cao  Trung binh       Thap
1     Thap  Trung binh       Thap        Cao  Trung binh       Thap
2     Thap  Trung binh        Cao       Thap         Cao       Thap
3      Cao  Trung binh       Thap        Cao        Thap        Cao
4     Thap  Trung binh        Cao       Thap         Cao       Thap

In [11]:
# Xử lý các categorical variables thành numerical variables

label_encoder = LabelEncoder()

for col in cols_X:
    X[col] = label_encoder.fit_transform(X[col])

In [12]:
model = RandomForestClassifier(n_estimators=2, random_state=1)

In [13]:
from sklearn.model_selection import train_test_split

# Lấy 90% dữ liệu để train, 10% còn lại để test.

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.1)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=2, random_state=1)

In [14]:
# Dự đoán với 10% dữ liệu đã tách ra ở bên trên

preds = model.predict(X_test)

In [15]:
#So sánh kết quả dự đoán với kết quả gốc
from sklearn.metrics import accuracy_score

print(f'Độ chính xác: {accuracy_score(y_test, preds) * 100}%')

Độ chính xác: 100.0%

In [16]:
X_test.head()

     Danh gia  Danh gia.1  Danh gia.2  Danh gia.3  Danh gia.4  Danh gia.5
192         2           1           0           2           0           2
256         1           1           0           1           0           1
169         2           1           2           0           2           2
67          2           1           2           2           2           2
201         0           1           1           0           1           0

In [17]:
y_test.head()

    Chan doan benh
192     Tieu duong
256     Tieu duong
169            Gut
67           Khong
201       Suy than

In [18]:
def chan_doan_benh(array):
    array = np.array(array)
    preds = model.predict(array.reshape(1, -1))
    if preds[0] == 'Gut':
        preds[0] = 'Gút'
    elif preds[0] == 'Tieu duong':
        preds[0] = 'Tiểu Đường'
    elif preds[0] == 'Suy than':
        preds[0] = 'Suy Thận'
    else:
        return 'Bạn không có nguy cơ mắc bệnh.'
    return f'Bạn có nguy cơ mắc bệnh {preds[0]}.'

<hr>
<b> TEST Ở BÊN DƯỚI</b><br>
<i>Input dưới dạng list<i><br>
1 - Thấp, 0 - Cao, 2 - Trung bình

In [19]:
print(chan_doan_benh([2,2,2,2,2,2]))

Bạn không có nguy cơ mắc bệnh.

<hr>